saturno: 5.1_saturno.c
	gcc -o 5.1_saturno 5.1_saturno.c -lm

juros: 5.2_juros.c
	gcc -o 5.2_juros 5.2_juros.c

ônibus: 5.3_ônibus.c
	gcc -o 5.3_ônibus 5.3_ônibus.c

notas: 5.4_notas.c
	gcc -o 5.4_notas 5.4_notas.c

fatorial: 5.5_fatorial.c
	gcc -o 5.5_fatorial 5.5_fatorial.c